a_studio_core_homepage:
    path:     /{_locale}
    defaults: 
        _controller: AStudioCoreBundle:Core:index
        _locale: fr
    requirements:
        _locale: fr|en

a_studio_core_contact:
    path:    /{_locale}/contact
    defaults: 
        _controller: AStudioCoreBundle:Core:contact
        _locale: fr
    requirements:
        -locale: fr|en
