a_studio_core_homepage:
    path:     /
    defaults: { _controller: AStudioCoreBundle:Core:index }
    
a_studio_core_contact:
    path:    /contact
    defaults: { _controller: AStudioCoreBundle:Core:contact }