a_studio_core:
    resource: "@AStudioCoreBundle/Resources/config/routing.yml"
    prefix:   /


a_studio_booking:
    resource: "@AStudioBookingBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/order
    requirements:
        _locale: fr|en


