# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:

services:
    a_studio_booking.validator.verifticket:
        class: AStudio\BookingBundle\Validator\VerifTicketValidator
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: validator.constraint_valid, alias: astudio_booking_verifticket }

    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

  