a_studio_booking_homepage:
    path:     /
    defaults: { _controller: AStudioBookingBundle:Order:index }

a_studio_booking_informations:
    path:    /informations
    defaults: {_controller: AStudioBookingBundle:Order:infos}

a_studio_booking_summary:
    path: /summary
    defaults: {_controller: AStudioBookingBundle:Order:summary }

a_studio_booking_confirm:
    path: /confirm
    defaults: {_controller: AStudioBookingBundle:Order:confirm }
